config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :restaurants do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
	member do
		put "like", to: "restaurants#upvote"
		put "dislike", to: "restaurants#downvote"
	end
    resources :restaurantimages
  end

  resources :street_foods do
    collection do
      get 'search'
    end
    resources :reviews, expect: [:show, :index]
  member do
    put "like", to: "street_foods#upvote"
    put "dislike", to: "street_foods#downvote"
  end
  end
  
  resources :bars do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
        member do
                put "like", to: "bars#upvote"
                put "dislike", to: "bars#downvote"
        end
  end

  post '/search/:query' => 'search#index'

  resources :places do
	collection do
		get 'search'
	end
	resources :reviews, expect: [:show, :index]
	member do
		put "like", to: "places#upvote"
		put "dislike", to: "places#downvote"
	end
end
  
  resources :touristspots do
	collection do
		get 'search'
	end
	resources :reviews, except: [:show, :index]
	member do
		put "like", to: "touristspots#upvote"
		put "dislike", to: "touristspots#downvote"
	end
	end

  resources :pubs do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
        member do
                put "like", to: "pubs#upvote"
                put "dislike", to: "pubs#downvote"
        end
  end

  resources :weekends do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
	member do
		put "like", to: "weekends#upvote"
		put "dislike", to: "weekends#downvote"
	end
  end

  get 'welcome/index'

  get 'pages/about'

  get 'pages/contact'
  get 'search' => 'search#index'

  root 'welcome#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	mount_uploader :image, ImageUploader

	mount_uploaders :restaurantimages, RestaurantimageUploader

	searchkick

	has_many :reviews, as: :reviewable, dependent: :destroy

	validates :name, :address, presence: true

	acts_as_votable
	geocoded_by :the_address
	def the_address
	"#{address} #{city} #{state} #{zipcode}"
	end

	after_validation :geocode, if: :address_changed?

#	def slug
 #   	  name.downcase.gsub(" ", "-")  
  #	end

  #	def to_param
   # 	  "#{id}-#{slug}"
  #	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:search, :index, :show]

  def search
    if params[:search].present?
      @restaurants = Restaurant.search(params[:search])
    else
      @restaurants = Restaurant.all
    end
  end

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
	@restaurant = Restaurant.find(params[:id])
	@reviews = @restaurant.reviews
    if @reviews.blank?
        @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

	def upvote
		@restaurant.upvote_by current_user
		redirect_to @restaurant
		end
		
	def downvote
		@restaurant.downvote_by current_user
		redirect_to @restaurant
		end
	
	
	
  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    


    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :address, :city, :state, :zipcode, :phone, :email, :parking, :image, :speciality, :reservation, :delivery, :ambience, :website, {restaurantimages: []})
    end

   # def upvote 
    #  @restaurant = Restaurant.find(params[:id])
    #  @restaurant.upvote_by current_user
    #  redirect_to :back
    #end  

    #def downvote
    #  @restaurant = Restaurant.find(params[:id])
    #  redirect_to :back
    #end
  
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant, :html => { multipart: true }) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h4>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if user_signed_in? && current_user.admin? %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %><br>
    <%= f.text_field :state, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :parking %><br>
    <%= f.text_field :parking, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :speciality %><br>
    <%= f.text_field :speciality, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :reservation %><br>
    <%= f.text_field :reservation, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :delivery %><br>
    <%= f.text_field :delivery, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :ambience %><br>
    <%= f.text_field :ambience, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :restaurantimage %><br>
    <%= f.file_field :restaurantimages, multiple: true %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>

    <% else %>

    <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %><br>
    <%= f.text_field :state, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :restaurantimage %><br>
    <%= f.file_field :restaurantimages, multiple: true %>
  </div>

  <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>

<% end %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant, class: "btn btn-link" %> |
<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<div class = "jumbotron">
  <h2>Socialye is the best way to share real reviews, and experiences with friends. </h2>
  <h4>Explore the favourite diners, pastery shops, Dhabas, Food Stalls and eateries in your areas.<br>
  Leave reviews about any place you visited, to help your friends over chossing the place to eat.</h4>
</div>

<div class="center">
  <div class="row">
  <% @restaurants.each do |restaurant| %>
      <div class="col-sm-6 col-md-3">
        <div class="card">
          <img class="card-img-top" data-src="<%= link_to image_tag(restaurant.image.thumb.url), restaurant %>
          <div class="card-block">
            <h3 class="card-title"><%= link_to restaurant.name.capitalize, restaurant %></h3>
            <p class="card-text">Description: <%= restaurant.description.capitalize %></p>
            <p class="card-text">Location: <%= restaurant.city.capitalize %></p>
        	  <div class="star-rating" data-score= <%= @avg_rating %> ></div>
	 </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<% if user_signed_in? && current_user.admin? %>

  <table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Zipcode</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Parking</th>
        <% if user_signed_in? && current_user.admin? %>
          <th colspan="2"></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @restaurants.each do |restaurant| %>
        <tr>
          <td><%= link_to restaurant.name, restaurant %></td>
          <td><%= restaurant.description %></td>
          <td><%= restaurant.address %></td>
          <td><%= restaurant.city %></td>
          <td><%= restaurant.state %></td>
          <td><%= restaurant.zipcode %></td>
          <td><%= restaurant.phone %></td>
          <td><%= restaurant.email %></td>
          <td><%= restaurant.parking %></td>
            <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

<br>

<% if user_signed_in? %>
<%= link_to 'Can\'t find the place you visited? You can add it here New Restaurant', new_restaurant_path, class: "btn btn-link" %>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/search.html.erb
<div class="center">
  <div class="row">
  <% @restaurants.each do |restaurant| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(restaurant.image.url), restaurant %>
          <div class="caption">
            <h3><%= link_to restaurant.name.capitalize, restaurant %></h3>
            <p><%= restaurant.description.capitalize %></p>
            <p><%= restaurant.city.capitalize %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<style>
  table {
    border-collapse: collapse;
  }
  
  tr {
    border-bottom: 1px solid #e3e3e3;
  }
</style>

<link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
<div class="container-fluid">
  <div class="row">
      <div class="col-md-8">
        <%= image_tag @restaurant.image_url %>   
      <br>
   <p>Restaurant Images</p>
     <% @restaurant.restaurantimages.each_with_index do |restaurantimage, index| %>
	<a data-toggle="modal" data-target="#myModal">
	 <%= image_tag(restaurantimage.thumb.url) %>
	</a>
     <% end %>
<br>
	<p>Add More Restaurants Pics</p>
	<%= form_for @restaurant, url: restaurant_restaurantimages_path(@restaurant), method: :post do |f| %>
	  <%= f.label :restaurantimage %>
	  <%= f.file_field :restaurantimages, multiple: true %>
	  <%= f.submit class: "btn btn-primary" %>
	<% end %>
<br>
      <br>
     <% if @reviews.blank? %>
      <h3> No reviews Yet. Be the first to give a reviews and help others</h3>
    <% else %>
      <h2> Reviews.</h2>
      <table class="table">
        <thead>
          <tr>

            <th class="col-md-3"></th>
            <th class="col-md-9"></th>
          </tr>
        </thead>

        <tbody class="frm-white">
          <% @reviews.each do |review| %>
              <tr>
                <td>
                    <div class="img-rounded">
                      <img src="<%= review.user.avatar_url %>">
                    </div> 

                  
                    <p><%= review.created_at.strftime("%-d/%-m/%-y") %></p>
                </td>

                <td>
                    <h4><strong>
                        <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
                    </strong>
                    </h4>
                      <div class="star-rating" data-score= <%= review.rating %> ></div>
                      <h5><p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p></h5>
								<%= social_share_button_tag(@restaurant.reviews) %>

                      <% if user_signed_in? %>
                        <% if (review.user == current_user) || (current_user.admin?) %>
                          <%= link_to "Edit", edit_restaurant_review_path(@restaurant, review) %>
                          <%= link_to "Delete", restaurant_review_path(@restaurant, review), method: :delete %>
                          <% end %>
                        <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    <% end %>
    </div>
    <br>
    <br>
    <div class="col-md-4">
     <div class="frm-white"> 
	 <div class="detail-overview-hearts">
                <h4><i class="fa fa-heart fa-2x"></i> <strong><%= @restaurant.get_upvotes.size %></strong> people love it
            </h4></div>
      <%= link_to "Give Heart", like_restaurant_path(@restaurant), class: "btn btn-success", method: :put %>

		  <%= link_to "Downvote", dislike_restaurant_path(@restaurant), 
      class: "btn btn-link", method: :put %>
    </div>
      
      <h2><strong>
          <%= @restaurant.name.capitalize %>
      </strong></h2><%= social_share_button_tag(@restaurant.name) %>

            <br>
    <div class="star-rating" data-score= <%= @avg_rating %> ></div>
    <p><%= "#{@reviews.length} reviews" %></p>

	<div class="frm-white">
    <p>
      <strong>Description:</strong>
      <%= @restaurant.description.capitalize %>
    </p>

    <p>
      <strong>City:</strong>
      <%= @restaurant.city.capitalize %>
    </p>

    <p>
      <strong>State:</strong>
      <%= @restaurant.state.capitalize %>
    </p>

    <p>
      <strong>Zipcode:</strong>
      <%= @restaurant.zipcode %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @restaurant.phone %>
    </p>

    <p>
      <strong>Website:</strong>
      <%= @restaurant.website %>
    </p>


    <p>
      <strong>Email:</strong>
      <%= @restaurant.email %>
    </p>

    <p>
      <strong>Parking:</strong>
      <%= @restaurant.parking %>
    </p>

    <p>
      <strong>Speciality:</strong>
      <%= @restaurant.speciality %>
    </p></div>

    <%= link_to "Write a Review", new_restaurant_review_path(@restaurant), class: "btn btn-success" %>

    <br>
    <br>

    <iframe
    width="296"
    height="230"
    frameborder="1" style="border:1"
    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDJ7BphNq_tVYF9JucYg93sM_xkeuMwR0w
      &q=<%= @restaurant.address.parameterize %>&zoom=14" allowfullscreen>
  </iframe>

  <br>
  <br>
  <div class="frm-white">
  <p>
      <strong>Take Reservation:</strong>
      <%= @restaurant.reservation %>
    </p>

    <p>
      <strong>Delivery:</strong>
      <%= @restaurant.delivery %>
    </p>

    <p>
      <strong>Ambience:</strong>
      <%= @restaurant.ambience %>
    </p>
	</div>

  </div>
</div>
</div>

    </div>
  </div>
  <%= link_to 'Edit', edit_restaurant_path(@restaurant), class: "btn btn-link" %> |
<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>
</div>

<% @restaurant.restaurantimages.each do |restaurantimage| %>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledb$
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="t$
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
                <%= image_tag(restaurantimage.url) %>
      </div>
      <div class="modal-footer">
                           <a class="btn btn-info modal-prev"> Previous</a>
                           <a class="btn btn-primary modal-next">Next <i class="icon-arrow-right icon-white"></i></a>
                <button type="button" class="btn btn-default" data-dismiss="modal">Clos$

      </div>
    </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<% end %>



<script>
  $('.star-rating').raty({
    path: 'http://socialye.blob.core.windows.net/stars', 
    readOnly: true,
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>