config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :restaurants do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
	member do
		put "like", to: "restaurants#upvote"
		put "dislike", to: "restaurants#downvote"
	end
    resources :restaurantimages
  end

  resources :street_foods do
    collection do
      get 'search'
    end
    resources :reviews, expect: [:show, :index]
  member do
    put "like", to: "street_foods#upvote"
    put "dislike", to: "street_foods#downvote"
  end
  end
  
  resources :bars do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
        member do
                put "like", to: "bars#upvote"
                put "dislike", to: "bars#downvote"
        end
  end

  post '/search/:query' => 'search#index'

  resources :places do
	collection do
		get 'search'
	end
	resources :reviews, expect: [:show, :index]
	member do
		put "like", to: "places#upvote"
		put "dislike", to: "places#downvote"
	end
end
  
  resources :touristspots do
	collection do
		get 'search'
	end
	resources :reviews, except: [:show, :index]
	member do
		put "like", to: "touristspots#upvote"
		put "dislike", to: "touristspots#downvote"
	end
	end

  resources :pubs do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
        member do
                put "like", to: "pubs#upvote"
                put "dislike", to: "pubs#downvote"
        end
  end

  resources :weekends do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
	member do
		put "like", to: "weekends#upvote"
		put "dislike", to: "weekends#downvote"
	end
  end

  get 'welcome/index'

  get 'pages/about'

  get 'pages/contact'
  get 'search' => 'search#index'

  root 'welcome#index'

end

app/models/pub.rb
class Pub < ActiveRecord::Base

	mount_uploader :pubhome, PubhomeUploader
#create another uploader and migrate it 
	searchkick

	has_many :reviews, as: :reviewable, dependent: :destroy

	validates :name, :address, presence: true

	acts_as_votable
	geocoded_by :the_address
	def the_address
	"#{address} #{zipcode}"
	end

	after_validation :geocode, if: :address_changed?

#	def slug
 #   	  name.downcase.gsub(" ", "-")  
  #	end
#
 # 	def to_param
  #  	  "#{id}-#{slug}"
  #	end
end

app/controllers/pubs_controller.rb
class PubsController < ApplicationController
  before_action :set_pub, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:search, :index, :show]

  def search
   if params[:search].present?
    @pubs = Pub.search(params[:search])
   else
    @pubs = Pub.all
   end
  end
 
  # GET /pubs
  # GET /pubs.json
  def index
    @pubs = Pub.all
  end

  # GET /pubs/1
  # GET /pubs/1.json
  def show
	@pub = Pub.find(params[:id])
	@reviews = @pub.reviews
    if @reviews.blank?
        @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /pubs/new
  def new
    @pub = Pub.new
  end

  # GET /pubs/1/edit
  def edit
  end

  # POST /pubs
  # POST /pubs.json
  def create
    @pub = Pub.new(pub_params)

    respond_to do |format|
      if @pub.save
        format.html { redirect_to @pub, notice: 'Pub was successfully created.' }
        format.json { render :show, status: :created, location: @pub }
      else
        format.html { render :new }
        format.json { render json: @pub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pubs/1
  # PATCH/PUT /pubs/1.json
  def update
    respond_to do |format|
      if @pub.update(pub_params)
        format.html { redirect_to @pub, notice: 'Pub was successfully updated.' }
        format.json { render :show, status: :ok, location: @pub }
      else
        format.html { render :edit }
        format.json { render json: @pub.errors, status: :unprocessable_entity }
      end
    end
  end

	def upvote
		@pub.upvote_by current_user
		redirect_to @pub
	end
		
	def downvote
		@pub.downvote_by current_user
		redirect_to @pub
	end

  # DELETE /pubs/1
  # DELETE /pubs/1.json
  def destroy
    @pub.destroy
    respond_to do |format|
      format.html { redirect_to pubs_url, notice: 'Pub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pub
      @pub = Pub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pub_params
      params.require(:pub).permit(:name, :address, :zipcode, :phone, :timing, :takesreservation, :parking, :goodforgroups, :ambience, :noiselevel, :goodfordancing, :alcoho, :happyhour, :smoking, :hastv, :bar, :pubhome)
    end
end

app/helpers/pubs_helper.rb
module PubsHelper
end

app/views/pubs/_form.html.erb
<%= form_for(@pub, :html => { multipart: true }) do |f| %>
  <% if @pub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pub.errors.count, "error") %> prohibited this pub from being saved:</h2>

      <ul>
      <% @pub.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if user_signed_in? && current_user.admin? %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :pubhome, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :timing %><br>
    <%= f.text_field :timing, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :takesreservation %><br>
    <%= f.text_field :takesreservation, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :parking %><br>
    <%= f.text_field :parking, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :goodforgroups %><br>
    <%= f.text_field :goodforgroups, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :ambience %><br>
    <%= f.text_field :ambience, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :noiselevel %><br>
    <%= f.text_field :noiselevel, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :goodfordancing %><br>
    <%= f.text_field :goodfordancing, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :alcoho %><br>
    <%= f.text_field :alcoho, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :happyhour %><br>
    <%= f.text_field :happyhour, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :smoking %><br>
    <%= f.text_field :smoking, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :hastv %><br>
    <%= f.text_field :hastv, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>

  <% else %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :pubhome, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :zipcode %><br> 
	<%= f.text_field :zipcode, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :timing %><br>
    <%= f.text_field :timing, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>


<% end %>
<% end %>

app/views/pubs/edit.html.erb
<h1>Editing Pub</h1>

<%= render 'form' %>

<%= link_to 'Show', @pub %> |
<%= link_to 'Back', pubs_path %>

app/views/pubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pubs</h1>
<div class="center">
  <div class="row">
  <% @pubs.each do |pub| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(pub.pubhome.thumb.url), pub %>
          <div class="caption">
            <h3><%= link_to pub.name.capitalize, pub %></h3>
            <p>Description: </p>
            <p>Location: <%= pub.address.capitalize %></p>
        	  <div class="star-rating" data-score= <%= @avg_rating %> ></div>
	 </div>
        </div>
      </div>
    <% end %>
  </div>
</div

<% if user_signed_in? && current_user.admin? %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Zipcode</th>
      <th>Phone</th>
      <th>Timing</th>
      <th>Takesreservation</th>
      <th>Parking</th>
      <th>Goodforgroups</th>
      <th>Ambience</th>
      <th>Noiselevel</th>
      <th>Goodfordancing</th>
      <th>Alcoho</th>
      <th>Happyhour</th>
      <th>Smoking</th>
      <th>Hastv</th>
      <th>Bar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pubs.each do |pub| %>
      <tr>
        <td><%= pub.name %></td>
        <td><%= pub.address %></td>
        <td><%= pub.zipcode %></td>
        <td><%= pub.phone %></td>
        <td><%= pub.timing %></td>
        <td><%= pub.takesreservation %></td>
        <td><%= pub.parking %></td>
        <td><%= pub.goodforgroups %></td>
        <td><%= pub.ambience %></td>
        <td><%= pub.noiselevel %></td>
        <td><%= pub.goodfordancing %></td>
        <td><%= pub.alcoho %></td>
        <td><%= pub.happyhour %></td>
        <td><%= pub.smoking %></td>
        <td><%= pub.hastv %></td>
        <td><%= pub.bar %></td>
        <td><%= link_to 'Show', pub %></td>
        <td><%= link_to 'Edit', edit_pub_path(pub) %></td>
        <td><%= link_to 'Destroy', pub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>
<% if user_signed_in? %>
<%= link_to 'New Pub', new_pub_path %>
<% end %>

app/views/pubs/new.html.erb
<h1>New Pub</h1>

<%= render 'form' %>

<%= link_to 'Back', pubs_path %>

app/views/pubs/search.html.erb
<div class="center">
  <div class="row">
  <% @pubs.each do |pub| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(pub.pubhome.thumb.url), pub %>
          <div class="caption">
            <h3><%= link_to pub.name.capitalize, pub %></h3>
            <p>Description: </p>
            <p>Location: <%= pub.address.capitalize %></p>
		</div>
        </div>
      </div>
    <% end %>
  </div>
</div

app/views/pubs/show.html.erb
<p id="notice"><%= notice %></p>

<style>
  table {
    border-collapse: collapse;
  }
  
  tr {
    border-bottom: 1px solid #e3e3e3;
  }
</style>

<link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
<div class="container-fluid">
  <div class="row">
      <div class="col-md-8">
        <%= image_tag @pub.pubhome_url %>   
      <br>
      <br>
     <% if @reviews.blank? %>
      <h3> No reviews Yet. Be the first to give a reviews and help others</h3>
    <% else %>
      <h2> Reviews.</h2>
      <table class="table">
        <thead>
          <tr>

            <th class="col-md-3"></th>
            <th class="col-md-9"></th>
          </tr>
        </thead>

        <tbody class="frm-white">
          <% @reviews.each do |review| %>
              <tr>
                <td>
                    <div class="img-rounded">
                      <img src="<%= review.user.avatar_url %>">
                    </div> 

                  
                    <p><%= review.created_at.strftime("%-d/%-m/%-y") %></p>
                </td>

                <td>
                    <h4><strong>
                        <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
                    </strong>
                    </h4>
                      <div class="star-rating" data-score= <%= review.rating %> ></div>
                      <h5><p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p></h5>
								<%= social_share_button_tag(@pub.reviews) %>

                      <% if user_signed_in? %>
                        <% if (review.user == current_user) || (current_user.admin?) %>
                          <%= link_to "Edit", edit_pub_review_path(@pub, review) %>
                          <%= link_to "Delete", pub_review_path(@pub, review), method: :delete %>
                          <% end %>
                        <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    <% end %>
    </div>
    <br>
    <br>
    <div class="col-md-4">
     <div class="frm-white"> 
	 <div class="detail-overview-hearts">
                <h4><i class="glyphicon glyphicon-heart"></i> <strong><%= @pub.get_upvotes.size %></strong> people love it
            </h4></div>
      <%= link_to "Give Heart", like_pub_path(@pub), class: "btn btn-success", method: :put %>

		  <%= link_to "Downvote", dislike_pub_path(@pub), 
      class: "btn btn-link", method: :put %>
    </div>


<h2>
  <strong><%= @pub.name %></strong>
  </h2><%= social_share_button_tag(@pub.name) %>
 <br>
    <div class="star-rating" data-score= <%= @avg_rating %> ></div>
    <p><%= "#{@reviews.length} reviews" %></p>

	<div class="frm-white">
<p>
  <strong>Address:</strong>
  <%= @pub.address %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @pub.zipcode %>
</p></div>

    <%= link_to "Write a Review", new_pub_review_path(@pub), class: "btn btn-success" %>

    <br>
    <br>

    <iframe
    width="296"
    height="230"
    frameborder="1" style="border:1"
    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDJ7BphNq_tVYF9JucYg93sM_xkeuMwR0w
      &q=<%= @pub.address.parameterize %>&zoom=14" allowfullscreen>
  </iframe>

  <br>
  <br>
  <div class="frm-white">
  <p>
  <strong>Phone:</strong>
  <%= @pub.phone %>
</p>

<p>
  <strong>Timing:</strong>
  <%= @pub.timing %>
</p>

<p>
  <strong>Takes Reservation:</strong>
  <%= @pub.takesreservation %>
</p>

<p>
  <strong>Parking:</strong>
  <%= @pub.parking %>
</p>

<p>
  <strong>Good for groups:</strong>
  <%= @pub.goodforgroups %>
</p>

<p>
  <strong>Ambience:</strong>
  <%= @pub.ambience %>
</p>

<p>
  <strong>Noise level:</strong>
  <%= @pub.noiselevel %>
</p>

<p>
  <strong>Good for dancing:</strong>
  <%= @pub.goodfordancing %>
</p>

<p>
  <strong>Alcohol:</strong>
  <%= @pub.alcoho %>
</p>

<p>
  <strong>Happy-hour:</strong>
  <%= @pub.happyhour %>
</p>

<p>
  <strong>Smoking:</strong>
  <%= @pub.smoking %>
</p>

<p>
  <strong>Has TV:</strong>
  <%= @pub.hastv %>
</p></div>

  </div>
</div>
</div>

    </div>
  </div>

<%= link_to 'Edit', edit_pub_path(@pub), class: "btn btn-link" %> |
<%= link_to 'Back', pubs_path, class: "btn btn-link" %>
</div>

<script>
  $('.star-rating').raty({
    path: 'http://socialye.blob.core.windows.net/stars', 
    readOnly: true,
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>