config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :restaurants do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
	member do
		put "like", to: "restaurants#upvote"
		put "dislike", to: "restaurants#downvote"
	end
    resources :restaurantimages
  end

  resources :street_foods do
    collection do
      get 'search'
    end
    resources :reviews, expect: [:show, :index]
  member do
    put "like", to: "street_foods#upvote"
    put "dislike", to: "street_foods#downvote"
  end
  end
  
  resources :bars do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
        member do
                put "like", to: "bars#upvote"
                put "dislike", to: "bars#downvote"
        end
  end

  post '/search/:query' => 'search#index'

  resources :places do
	collection do
		get 'search'
	end
	resources :reviews, expect: [:show, :index]
	member do
		put "like", to: "places#upvote"
		put "dislike", to: "places#downvote"
	end
end
  
  resources :touristspots do
	collection do
		get 'search'
	end
	resources :reviews, except: [:show, :index]
	member do
		put "like", to: "touristspots#upvote"
		put "dislike", to: "touristspots#downvote"
	end
	end

  resources :pubs do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
        member do
                put "like", to: "pubs#upvote"
                put "dislike", to: "pubs#downvote"
        end
  end

  resources :weekends do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
	member do
		put "like", to: "weekends#upvote"
		put "dislike", to: "weekends#downvote"
	end
  end

  get 'welcome/index'

  get 'pages/about'

  get 'pages/contact'
  get 'search' => 'search#index'

  root 'welcome#index'

end

app/models/weekend.rb
class Weekend < ActiveRecord::Base

	mount_uploader :weekendhangout, WeekendhangoutUploader
	validates :name, :address, presence: true

	searchkick
	
	has_many :reviews, as: :reviewable, dependent: :destroy
	acts_as_votable

	geocoded_by :address

	after_validation :geocode, if: :address_changed?
#	def slug
 #   	  name.downcase.gsub(" ", "-")  
  #	end

  #	def to_param
   # 	  "#{id}-#{slug}"
  #	end

end

app/controllers/weekends_controller.rb
class WeekendsController < ApplicationController
  before_action :set_weekend, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:search, :index, :show]

  def search
    if params[:search].present?
       @weekends = Weekend.search(params[:search])
    else
       @weekends = Weekend.all
    end
  end

  # GET /weekends
  # GET /weekends.json
  def index
    @weekends = Weekend.all
  end

  # GET /weekends/1
  # GET /weekends/1.json
  def show
  	@weekend = Weekend.find(params[:id])
	@reviews = @weekend.reviews
    if @reviews.blank?
        @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /weekends/new
  def new
    @weekend = Weekend.new
  end

  # GET /weekends/1/edit
  def edit
  end

  # POST /weekends
  # POST /weekends.json
  def create
    @weekend = Weekend.new(weekend_params)

    respond_to do |format|
      if @weekend.save
        format.html { redirect_to @weekend, notice: 'Weekend was successfully created.' }
        format.json { render :show, status: :created, location: @weekend }
      else
        format.html { render :new }
        format.json { render json: @weekend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weekends/1
  # PATCH/PUT /weekends/1.json
  def update
    respond_to do |format|
      if @weekend.update(weekend_params)
        format.html { redirect_to @weekend, notice: 'Weekend was successfully updated.' }
        format.json { render :show, status: :ok, location: @weekend }
      else
        format.html { render :edit }
        format.json { render json: @weekend.errors, status: :unprocessable_entity }
      end
    end
  end
    def upvote
		@weekend.upvote_by current_user
		redirect_to @weekend
	end
		
	def downvote
		@weekend.downvote_by current_user
		redirect_to @weekend
	end
  # DELETE /weekends/1
  # DELETE /weekends/1.json
  def destroy
    @weekend.destroy
    respond_to do |format|
      format.html { redirect_to weekends_url, notice: 'Weekend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weekend
      @weekend = Weekend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weekend_params
      params.require(:weekend).permit(:name, :address, :description, :placesvisited, :weekendhangout)
    end
end

app/helpers/weekends_helper.rb
module WeekendsHelper
end

app/views/weekends/_form.html.erb
<%= form_for(@weekend, :html => { multipart: true }) do |f| %>
  <% if @weekend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weekend.errors.count, "error") %> prohibited this weekend from being saved:</h2>

      <ul>
      <% @weekend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
	<%= f.file_field :weekendhangout, class: "form-control" %>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/weekends/edit.html.erb
<h1>Editing Weekend</h1>

<%= render 'form' %>

<%= link_to 'Show', @weekend %> |
<%= link_to 'Back', weekends_path %>

app/views/weekends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Weekends</h1>

<div class="center">
  <div class="row">
  <% @weekends.each do |weekend| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(weekend.weekendhangout.thumb.url), weekend %>
          <div class="caption">
            <h3><%= link_to weekend.name.capitalize, weekend %></h3>
            <p>Description: </p>
            <p>Location: <%= weekend.address.capitalize %></p>
        	  <div class="star-rating" data-score= <%= @avg_rating %> ></div>
	 </div>
        </div>
      </div>
    <% end %>
  </div>
</div

<% if user_signed_in? && current_user.admin? %>

<table>
  <thead>
    <tr>
      <th>Hangouts</th>
      <th>Name</th>
      <th>Address</th>
      <th>Description</th>
      <th>Placesvisited</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weekends.each do |weekend| %>
      <tr>
        <td><%= weekend.Hangouts %></td>
        <td><%= weekend.name %></td>
        <td><%= weekend.address %></td>
        <td><%= weekend.description %></td>
        <td><%= weekend.placesvisited %></td>
        <td><%= link_to 'Show', weekend %></td>
        <td><%= link_to 'Edit', edit_weekend_path(weekend) %></td>
        <td><%= link_to 'Destroy', weekend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>
<% if user_signed_in? %>
<%= link_to 'New Weekend', new_weekend_path %>
<% end %>

app/views/weekends/new.html.erb
<h1>New Weekend</h1>

<%= render 'form' %>

<%= link_to 'Back', weekends_path %>

app/views/weekends/search.html.erb
<div class="center">
  <div class="row">
  <% @weekends.each do |weekend| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(weekend.weekendhangout.thumb.url), weekend %>
          <div class="caption">
            <h3><%= link_to weekend.name.capitalize, weekend %></h3>
            <p>Description: </p>
            <p>Location: <%= weekend.address.capitalize %></p>
        	  <div class="star-rating" data-score= <%= @avg_rating %> ></div>
	 </div>
        </div>
      </div>
    <% end %>
  </div>
</div

app/views/weekends/show.html.erb
<style>
  table {
    border-collapse: collapse;
  }
  
  tr {
    border-bottom: 1px solid #e3e3e3;
  }
</style>

<link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
<div class="container-fluid">
  <div class="row">
      <div class="col-md-8">
      <%= image_tag @weekend.weekendhangout_url %>   
      <br>
      <br>
       <% if @reviews.blank? %>
      <h3> No reviews Yet for this Place. If you have been there then, Be the first to give a reviews and help others</h3>
    <% else %>
      <h2> Reviews.</h2>
      <table class="table">
        <thead>
          <tr>

            <th class="col-md-3"></th>
            <th class="col-md-9"></th>
          </tr>
        </thead>

        <tbody class="frm-white">
          <% @reviews.each do |review| %>
              <tr>
                <td>
                    <div class="img-rounded">
                      <img src="<%= review.user.avatar_url %>">
                    </div> 

                  
                    <p><%= review.created_at.strftime("%-d/%-m/%-y") %></p>
                </td>

                <td>
                    <h4><strong>
                        <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
                    </strong>
                    </h4>
                      <div class="star-rating" data-score= <%= review.rating %> ></div>
                      <h5><p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p></h5>
								<%= social_share_button_tag(@weekend.reviews) %>

                      <% if user_signed_in? %>
                        <% if (review.user == current_user) || (current_user.admin?) %>
                          <%= link_to "Edit", edit_weekend_review_path(@weekend, review) %>
                          <%= link_to "Delete", weekend_review_path(@weekend, review), method: :delete %>
                          <% end %>
                        <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    <% end %>
    </div>
    <br>
    <br>
	<div class="col-md-4">

		<div class="frm-white"> 
		<div class="detail-overview-hearts">
                <h4><i class="glyphicon glyphicon-heart"></i> <strong><%= @weekend.get_upvotes.size %></strong> people love it
            </h4></div>
		  <%= link_to "Give Heart", like_weekend_path(@weekend), class: "btn btn-success", method: :put %>

			  <%= link_to "Downvote", dislike_weekend_path(@weekend), 
				class: "btn btn-link", method: :put %>
		</div>
      
      <h2><strong>
          <%= @weekend.name.capitalize %>
      </strong></h2><%= social_share_button_tag(@weekend.name) %>

		    
    <div class="star-rating" data-score= <%= @avg_rating %> ></div>
    <p><%= "#{@reviews.length} reviews" %></p>

	<div class="frm-white">
    <p>
      <strong>Address:</strong>
      <%= @weekend.address.capitalize %>
    </p>
	
	<p><strong>Description:</strong>
		<%= @weekend.description %>
	</p>
	</div>

    <%= link_to "Write a Review", new_weekend_review_path(@weekend), class: "btn btn-success" %>

    <br>
    <br>

    <iframe
    width="296"
    height="230"
    frameborder="1" style="border:1"
    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDJ7BphNq_tVYF9JucYg93sM_xkeuMwR0w
      &q=<%= @weekend.address.parameterize %>&zoom=14" allowfullscreen>
  </iframe>

  <br>
  <br>
</div>
</div>
</div>
<%= link_to 'Edit Details', edit_weekend_path(@weekend), class: "btn btn-link" %> |
<%= link_to 'Back', weekends_path, class: "btn btn-link" %>


<script>
  $('.star-rating').raty({
    path: 'http://socialye.blob.core.windows.net/stars', 
    readOnly: true,
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>