config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :restaurants do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
	member do
		put "like", to: "restaurants#upvote"
		put "dislike", to: "restaurants#downvote"
	end
    resources :restaurantimages
  end

  resources :street_foods do
    collection do
      get 'search'
    end
    resources :reviews, expect: [:show, :index]
  member do
    put "like", to: "street_foods#upvote"
    put "dislike", to: "street_foods#downvote"
  end
  end
  
  resources :bars do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
        member do
                put "like", to: "bars#upvote"
                put "dislike", to: "bars#downvote"
        end
  end

  post '/search/:query' => 'search#index'

  resources :places do
	collection do
		get 'search'
	end
	resources :reviews, expect: [:show, :index]
	member do
		put "like", to: "places#upvote"
		put "dislike", to: "places#downvote"
	end
end
  
  resources :touristspots do
	collection do
		get 'search'
	end
	resources :reviews, except: [:show, :index]
	member do
		put "like", to: "touristspots#upvote"
		put "dislike", to: "touristspots#downvote"
	end
	end

  resources :pubs do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
        member do
                put "like", to: "pubs#upvote"
                put "dislike", to: "pubs#downvote"
        end
  end

  resources :weekends do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
	member do
		put "like", to: "weekends#upvote"
		put "dislike", to: "weekends#downvote"
	end
  end

  get 'welcome/index'

  get 'pages/about'

  get 'pages/contact'
  get 'search' => 'search#index'

  root 'welcome#index'

end

app/models/place.rb
class Place < ActiveRecord::Base
	mount_uploader :placesvisited, PlacesvisitedUploader
	validates :name, :address, presence: true

	searchkick
	
	has_many :reviews, as: :reviewable, dependent: :destroy
	acts_as_votable

	geocoded_by :address

	after_validation :geocode, if: :address_changed?
#	def slug
 #   	  name.downcase.gsub(" ", "-")  
  #	end

  #	def to_param
   # 	  "#{id}-#{slug}"
  #	end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:search, :index, :show]
  
  def search
    if params[:search].present?
      @places = Place.search(params[:search])
    else
      @places = Place.all
    end
  end


  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
	@place = Place.find(params[:id])
	@reviews = @place.reviews
		if @reviews.blank?
			@avg_rating = 0
		else
		  @avg_rating = @reviews.average(:rating).round(2)
		end
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def upvote
		@place.upvote_by current_user
		redirect_to @place
	end
		
	def downvote
		@place.downvote_by current_user
		redirect_to @place
	end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :address, :description, :placesvisited)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place, :html => { multipart: true }) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :placesvisited, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
  
  <% end %>


  

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Places</h1>

<div class = "jumbotron">
  <h2>ReviewApp is the best way to know real reviews, from foodies like you.</h2>
  <h4>Explore the favourite diners, pastery shops, Dhabas, Food Stalls and eateries in your areas.<br>
  Leave reviews about any place you visited, to help your friends over chossing the place to eat.</h4>
</div>

<div class="center">
  <div class="row">
  <% @places.each do |place| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(place.placesvisited.thumb.url), place %>
          <div class="caption">
            <h3><%= link_to place.name.capitalize, place %></h3>
            <p><%= place.address.capitalize %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<% if user_signed_in? && current_user.admin? %>

  <table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Address</th>
        
        <% if user_signed_in? && current_user.admin? %>
          <th colspan="2"></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @places.each do |place| %>
        <tr>
          <td><%= link_to place.name, place %></td>
          <td><%= place.description %></td>
          <td><%= place.address %></td>
        
            <td><%= link_to 'Edit', edit_place_path(place) %></td>
          <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

<br>
<% if user_signed_in? %>
<%= link_to 'Add New Places Here', new_place_path, class: "btn btn-link" %>
<% end %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<style>
  table {
    border-collapse: collapse;
  }
  
  tr {
    border-bottom: 1px solid #e3e3e3;
  }
</style>

<link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
<div class="container-fluid">
  <div class="row">
      <div class="col-md-8">
      <%= image_tag @place.placesvisited_url %>   
      <br>
      <br>
       <% if @reviews.blank? %>
      <h3> No reviews Yet for this Place. If you have been there then, Be the first to give a reviews and help others</h3>
    <% else %>
      <h2> Reviews.</h2>
      <table class="table">
        <thead>
          <tr>

            <th class="col-md-3"></th>
            <th class="col-md-9"></th>
          </tr>
        </thead>

        <tbody class="frm-white">
          <% @reviews.each do |review| %>
              <tr>
                <td>
                    <div class="img-rounded">
                      <img src="<%= review.user.avatar_url %>">
                    </div> 

                  
                    <p><%= review.created_at.strftime("%-d/%-m/%-y") %></p>
                </td>

                <td>
                    <h4><strong>
                        <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
                    </strong>
                    </h4>
                      <div class="star-rating" data-score= <%= review.rating %> ></div>
                      <h5><p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p></h5>
								<%= social_share_button_tag(@place.reviews) %>

                      <% if user_signed_in? %>
                        <% if (review.user == current_user) || (current_user.admin?) %>
                          <%= link_to "Edit", edit_place_review_path(@place, review) %>
                          <%= link_to "Delete", place_review_path(@place, review), method: :delete %>
                          <% end %>
                        <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    <% end %>
    </div>
    <br>
    <br>
	<div class="col-md-4">

		<div class="frm-white"> 
		<div class="detail-overview-hearts">
                <h4><i class="glyphicon glyphicon-heart"></i> <strong><%= @place.get_upvotes.size %></strong> people love it
            </h4></div>
		  <%= link_to "Give Heart", like_place_path(@place), class: "btn btn-success", method: :put %>

			  <%= link_to "Downvote", dislike_place_path(@place), 
				class: "btn btn-link", method: :put %>
		</div>
      
      <h2><strong>
          <%= @place.name.capitalize %>
      </strong></h2><%= social_share_button_tag(@place.name) %>

		    
    <div class="star-rating" data-score= <%= @avg_rating %> ></div>
    <p><%= "#{@reviews.length} reviews" %></p>

	<div class="frm-white">
    <p>
      <strong>Address:</strong>
      <%= @place.address.capitalize %>
    </p>
	
	<p><strong>Description:</strong>
		<%= @place.description %>
	</p>
	</div>

    <%= link_to "Write a Review", new_place_review_path(@place), class: "btn btn-success" %>

    <br>
    <br>

    <iframe
    width="296"
    height="230"
    frameborder="1" style="border:1"
    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDJ7BphNq_tVYF9JucYg93sM_xkeuMwR0w
      &q=<%= @place.address.parameterize %>&zoom=14" allowfullscreen>
  </iframe>

  <br>
  <br>
</div>
</div>
</div>
<%= link_to 'Edit Details', edit_place_path(@place), class: "btn btn-link" %> |
<%= link_to 'Back', places_path, class: "btn btn-link" %>


<script>
  $('.star-rating').raty({
    path: 'http://socialye.blob.core.windows.net/stars', 
    readOnly: true,
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>